apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-deployment
  labels:
    app: pokemon
  namespace: container-lab-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pokemon
  template:
    metadata:
      labels:
        app: pokemon
    spec:
      containers:
      - name: pokemon
        image: ciberado/pokemon-nodejs
        ports:
        - containerPort: 80