apiVersion: v1
kind: Service
metadata:
  name: pokemon-service
  namespace: container-lab-ns
spec:
  type: NodePort
  selector:
    app: pokemon
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30007